default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bycoders_transactions_development

test:
  <<: *default
  database: bycoders_transactions_test

production:
  <<: *default
  database: bycoders_transactions_production
  username: bycoders_transactions
  password: <%= ENV['BYCODERS_TRANSACTIONS_DATABASE_PASSWORD'] %>
